In [ ]:
import zipfile

zip_ref = zipfile.ZipFile("Food-101-minimized-main (2).zip")
zip_ref.extractall()
zip_ref.close()

In [ ]:
import os
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

def load_and_preprocess_images(folder_path, image_size=(64, 64)):
    images = []
    labels = []

    for class_folder in os.listdir(folder_path):
        class_path = os.path.join(folder_path, class_folder)

        if os.path.isdir(class_path):
            for image_file in os.listdir(class_path):
                image_path = os.path.join(class_path, image_file)

                # Load and resize the image
                image = Image.open(image_path).resize(image_size)

                # Convert the image to a numpy array and normalize pixel values
                image_array = np.array(image) / 255.0

                # Append the image array to the list
                images.append(image_array)

                # Append the corresponding label
                labels.append(class_folder)

    # Convert labels to numerical format
    label_encoder = LabelEncoder()
    encoded_labels = label_encoder.fit_transform(labels)

    return np.array(images), encoded_labels


train_folder_path = '/content/Food-101-minimized-main/train'
test_folder_path = '/content/Food-101-minimized-main/test'

# Load and preprocess training data
images_tr, labels_tr = load_and_preprocess_images(train_folder_path)

# Load and preprocess test data
images_ts, labels_ts = load_and_preprocess_images(test_folder_path)

# Split the data into train and validation sets
X_train, X_test, y_train, y_test = train_test_split(images_tr, labels_tr, test_size=0.2, random_state=42)


print("X_train shape:", X_train.shape)

print("X_test shape:", X_test.shape)


X_train shape: (2800, 64, 64, 3)
X_test shape: (700, 64, 64, 3)


In [ ]:

X_train_flatten = X_train.reshape(X_train.shape[0], -1)

X_test_flatten = X_test.reshape(X_test.shape[0], -1)


print("Flattened X_train shape:", X_train_flatten.shape)

print("Flattened X_test shape:", X_test_flatten.shape)




Flattened X_train shape: (2800, 12288)
Flattened X_test shape: (700, 12288)


In [ ]:
X_train_flatten

array([[0.29411765, 0.1254902 , 0.05098039, ..., 0.07058824, 0.10588235,
        0.09019608],
       [0.76862745, 0.50196078, 0.23921569, ..., 0.36862745, 0.1372549 ,
        0.02352941],
       [0.01568627, 0.01568627, 0.01960784, ..., 0.49803922, 0.48627451,
        0.52156863],
       ...,
       [0.35294118, 0.38823529, 0.36470588, ..., 0.45882353, 0.38431373,
        0.28235294],
       [0.96862745, 0.96862745, 0.96862745, ..., 0.94901961, 0.94901961,
        0.94901961],
       [0.15294118, 0.2627451 , 0.44313725, ..., 0.00392157, 0.0627451 ,
        0.19215686]])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np


# Create and train logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', C=1.0)

# Train the model
model.fit(X_train_flatten, y_train)
# Make predictions
y_pred = model.predict(X_test_flatten)

# Print the classification report
print(classification_report(y_test, y_pred))

# Print the confusion matrix
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.33      0.36      0.34       138
           1       0.38      0.34      0.36       167
           2       0.29      0.29      0.29       138
           3       0.47      0.40      0.43       137
           4       0.37      0.44      0.40       120

    accuracy                           0.36       700
   macro avg       0.37      0.37      0.37       700
weighted avg       0.37      0.36      0.36       700

[[50 26 27 13 22]
 [37 57 38 12 23]
 [25 33 40 21 19]
 [22 19 16 55 25]
 [19 14 18 16 53]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
